version: '3'
services:
  web:
    build: .
    ports:
     - "5000:80"
    environment:
      - PORT=80
      - DATABASE_URL=postgres://sa:Passw0rd@db:5432/todo
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=Passw0rd
      - POSTGRES_USER=sa
