version: '3'
services:
  web:
    build: .
    ports:
     - "5000:80"
    environment:
      - PORT=80
  db:
    image: "microsoft/mssql-server-linux"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd