version: '3'
services:
  web:
    build: .
    ports:
     - "5000:80"
    environment:
      - PORT=80
      - CONNECTION_STRING=Server=db;Database=todo;User=sa;Password=Passw0rd;MultipleActiveResultSets=true
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Passw0rd
